input = input.txt
output = output.txt

main: lexer.l parser.y
	bison -d parser.y 
	flex lexer.l 
	gcc parser.tab.c lex.yy.c
	a <$(input)> $(output)

assembler:
	C:\masm32\bin\ml /c /coff /Cp q1b.asm
	C:\masm32\bin\link -entry:main /subsystem:console q1b.obj
	q1b
	


