
assembler:
	C:\masm32\bin\ml /c /coff /Cp prog1.asm
	C:\masm32\bin\link -entry:main /subsystem:console prog1.obj
	prog1
	


	C:\masm32\bin\ml /c /coff /Cp prog2.asm
	C:\masm32\bin\link -entry:main /subsystem:console prog2.obj
	prog2
	

	C:\masm32\bin\ml /c /coff /Cp prog3.asm
	C:\masm32\bin\link -entry:main /subsystem:console prog3.obj
	prog3
	
	C:\masm32\bin\ml /c /coff /Cp prog4.asm
	C:\masm32\bin\link -entry:main /subsystem:console prog4.obj
	prog4
	

	C:\masm32\bin\ml /c /coff /Cp prog5.asm
	C:\masm32\bin\link -entry:main /subsystem:console prog5.obj
	prog5